# Generated by Django 5.2.4 on 2025-07-18 12:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان مکان')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='عرض جغرافیایی')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='طول جغرافیایی')),
            ],
            options={
                'verbose_name': 'مکان',
                'verbose_name_plural': 'مکان\u200cها',
            },
        ),
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره موبایل')),
                ('code', models.CharField(max_length=128, verbose_name='کد هش\u200cشده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('purpose', models.CharField(choices=[('registration', 'ثبت\u200cنام'), ('login', 'ورود'), ('change_phone', 'تغییر شماره')], default='registration', max_length=20, verbose_name='هدف کد')),
                ('failed_attempts', models.IntegerField(default=0, verbose_name='تلاش\u200cهای ناموفق')),
            ],
            options={
                'verbose_name': 'کد تأیید',
                'verbose_name_plural': 'کدهای تأیید',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='شماره موبایل')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='تأیید شماره موبایل')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('role', models.CharField(choices=[('super_admin', 'سوپر ادمین'), ('admin', 'ادمین'), ('education_admin', 'آموزش و پرورش'), ('transport_admin', 'اداره حمل\u200cونقل'), ('school_admin', 'مدیر مدرسه'), ('parent', 'والد'), ('student', 'دانش\u200cآموز'), ('driver', 'راننده')], default='parent', max_length=30, verbose_name='نقش کاربر')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد ملی')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('referral_code', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='کد دعوت')),
                ('used_referral_code', models.CharField(blank=True, max_length=12, null=True, verbose_name='کد دعوت استفاده\u200cشده')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('inviter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitees', to=settings.AUTH_USER_MODEL, verbose_name='دعوت\u200cکننده')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ['role', 'phone_number'],
            },
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='شماره پلاک')),
                ('car_type', models.CharField(max_length=50, verbose_name='نوع خودرو')),
                ('national_card_image', models.ImageField(upload_to='drivers/national_cards/', verbose_name='عکس کارت ملی')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='drivers/photos/', verbose_name='عکس پروفایل')),
                ('license_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع گواهینامه')),
                ('license_expiry_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضای گواهینامه')),
                ('vehicle_insurance_image', models.ImageField(blank=True, null=True, upload_to='drivers/insurance/', verbose_name='بیمه خودرو')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تأیید صلاحیت راننده')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='امتیاز راننده')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر راننده')),
            ],
            options={
                'verbose_name': 'پروفایل راننده',
                'verbose_name_plural': 'پروفایل\u200cهای راننده',
            },
        ),
        migrations.CreateModel(
            name='EducationAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100, verbose_name='نام منطقه')),
                ('can_manage_permissions', models.BooleanField(default=True, verbose_name='مدیریت دسترسی\u200cها')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر آموزش و پرورش')),
            ],
            options={
                'verbose_name': 'پروفایل آموزش و پرورش',
                'verbose_name_plural': 'پروفایل\u200cهای آموزش و پرورش',
            },
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('father', 'پدر'), ('mother', 'مادر'), ('guardian', 'قیم')], default='father', max_length=50, verbose_name='نوع رابطه با دانش\u200cآموز')),
                ('default_driver', models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_default_driver', to=settings.AUTH_USER_MODEL, verbose_name='راننده پیش\u200cفرض')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر والد')),
            ],
            options={
                'verbose_name': 'پروفایل والد',
                'verbose_name_plural': 'پروفایل\u200cهای والد',
            },
        ),
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=150, verbose_name='نام مدرسه')),
                ('school_phone', models.CharField(max_length=20, verbose_name='شماره تماس مدرسه')),
                ('school_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد مدرسه')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='ساعت شروع مدرسه')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='ساعت پایان مدرسه')),
                ('school_type', models.CharField(choices=[('public', 'دولتی'), ('private', 'غیردولتی'), ('special', 'استثنایی')], default='public', max_length=50, verbose_name='نوع مدرسه')),
                ('school_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.location', verbose_name='لوکیشن مدرسه')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر مدرسه/مدیر')),
            ],
            options={
                'verbose_name': 'پروفایل مدرسه',
                'verbose_name_plural': 'پروفایل\u200cهای مدرسه',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=20, verbose_name='پایه تحصیلی')),
                ('class_name', models.CharField(max_length=50, verbose_name='نام کلاس')),
                ('school_id_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد دانش\u200cآموزی')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال')),
                ('special_conditions', models.TextField(blank=True, null=True, verbose_name='شرایط خاص (اختیاری)')),
                ('default_driver', models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_default_driver', to=settings.AUTH_USER_MODEL, verbose_name='راننده پیش\u200cفرض')),
                ('home_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_home', to='users.location', verbose_name='لوکیشن منزل')),
                ('school_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_school', to='users.location', verbose_name='لوکیشن مدرسه')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'پروفایل دانش\u200cآموز',
                'verbose_name_plural': 'پروفایل\u200cهای دانش\u200cآموز',
            },
        ),
        migrations.CreateModel(
            name='SuperAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_all', models.BooleanField(default=True, verbose_name='دسترسی کامل مدیریتی')),
                ('can_view_logs', models.BooleanField(default=True, verbose_name='دسترسی مشاهده لاگ\u200cها')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر سوپر ادمین')),
            ],
            options={
                'verbose_name': 'پروفایل سوپر ادمین',
                'verbose_name_plural': 'پروفایل\u200cهای سوپر ادمین',
            },
        ),
        migrations.CreateModel(
            name='TransportAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100, verbose_name='نام منطقه')),
                ('total_active_drivers', models.PositiveIntegerField(default=0, verbose_name='تعداد رانندگان فعال')),
                ('region_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.location', verbose_name='لوکیشن منطقه')),
                ('schools', models.ManyToManyField(blank=True, to='users.schoolprofile', verbose_name='مدارس زیرمجموعه')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر اداره حمل و نقل')),
            ],
            options={
                'verbose_name': 'پروفایل اداره حمل و نقل',
                'verbose_name_plural': 'پروفایل\u200cهای اداره حمل و نقل',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code_used', models.CharField(max_length=12, verbose_name='کد رفرال استفاده\u200cشده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ دعوت')),
                ('invited', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='received_referral', to=settings.AUTH_USER_MODEL, verbose_name='دعوت\u200cشده')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_referrals', to=settings.AUTH_USER_MODEL, verbose_name='دعوت\u200cکننده')),
            ],
            options={
                'verbose_name': 'دعوت\u200cنامه',
                'verbose_name_plural': 'دعوت\u200cنامه\u200cها',
                'ordering': ['-created_at'],
                'unique_together': {('inviter', 'invited')},
            },
        ),
    ]
