# Generated by Django 5.2.4 on 2025-07-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='car_type',
            field=models.CharField(choices=[('van', 'ون'), ('car', 'سواری'), ('minibus', 'مینی\u200cبوس')], default='car', max_length=50, verbose_name='نوع خودرو'),
        ),
    ]
