# Generated by Django 5.2.4 on 2025-07-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_driverprofile_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'سوپر ادمین'), ('admin', 'ادمین'), ('education_admin', 'آموزش و پرورش'), ('transport_admin', 'اداره حمل\u200cونقل'), ('school_admin', 'مدیر مدرسه'), ('parent', 'والد'), ('student', 'دانش\u200cآموز'), ('driver', 'راننده')], default='driver', max_length=30, verbose_name='نقش کاربر'),
        ),
    ]
