# Generated by Django 5.2.4 on 2025-07-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='national_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/national_cards/', verbose_name='عکس کارت ملی'),
        ),
    ]
