# Generated by Django 5.2.4 on 2025-07-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_driverprofile_national_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='امتیاز راننده'),
        ),
    ]
