# Generated by Django 5.2.4 on 2025-07-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_driverprofile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='purpose',
            field=models.CharField(choices=[('registration', 'ثبت\u200cنام'), ('login', 'ورود'), ('change_phone', 'تغییر شماره'), ('resend_otp', 'ارسال مجدد')], default='registration', max_length=20, verbose_name='هدف کد'),
        ),
    ]
