# Generated by Django 5.2.4 on 2025-07-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_phoneotp_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=15, verbose_name='شماره موبایل'),
        ),
    ]
