# Generated by Django 5.2.4 on 2025-07-23 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_phoneotp_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='school_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_school', to='users.location', verbose_name='لوکیشن مدرسه'),
        ),
    ]
