# Generated by Django 5.2.4 on 2025-07-22 13:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pin_code_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('pin_code_expiry', models.DateTimeField(blank=True, null=True)),
                ('withdraw_limit_per_day', models.DecimalField(decimal_places=2, default=1000000, max_digits=12)),
                ('withdrawn_today', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_withdraw_reset', models.DateTimeField(default=django.utils.timezone.now)),
                ('currency', models.CharField(default='IRR', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('closed', 'Closed')], default='active', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_logs', to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', 'واریز'), ('withdraw', 'برداشت'), ('transfer', 'انتقال'), ('reward', 'هدیه'), ('fee', 'کارمزد'), ('refund', 'بازگشت وجه')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('previous_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('completed', 'کامل شده'), ('failed', 'ناموفق'), ('reversed', 'برگشت خورده')], default='pending', max_length=20)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('integrity_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_reversed', models.BooleanField(default=False)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_wallet_transactions', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_wallet_transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet')),
            ],
        ),
    ]
