# Generated by Django 5.2.4 on 2025-08-06 12:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('currency', models.CharField(default='IRR', max_length=10)),
                ('status', models.CharField(choices=[('active', 'فعال'), ('frozen', 'مسدود شده'), ('closed', 'بسته شده')], default='active', max_length=10)),
                ('withdraw_limit_per_day', models.DecimalField(decimal_places=2, default=1000000, max_digits=18)),
                ('withdrawn_today', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('last_withdraw_reset', models.DateTimeField(default=django.utils.timezone.now)),
                ('pin_code_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('pin_code_expiry', models.DateTimeField(blank=True, null=True)),
                ('failed_pin_attempts', models.IntegerField(default=0)),
                ('last_failed_attempt', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ' کیف پول',
                'verbose_name_plural': ' کیف پول',
            },
        ),
        migrations.CreateModel(
            name='WalletErrorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_type', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_logs', to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='WalletOperationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('deposit', 'واریز'), ('withdraw', 'برداشت'), ('transfer', 'انتقال'), ('pin_set', 'تنظیم رمز'), ('pin_verify', 'تایید رمز'), ('reward', 'پاداش'), ('fee', 'کارمزد'), ('refund', 'بازگشت وجه'), ('other', 'سایر')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='مبلغ مربوط به عملیات (در صورت وجود)', max_digits=18, null=True)),
                ('status', models.CharField(choices=[('success', 'موفق'), ('failure', 'ناموفق')], default='success', max_length=10)),
                ('message', models.TextField(blank=True, help_text='توضیح یا پیام مرتبط با عملیات')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='آدرس IP درخواست\u200cدهنده', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='اطلاعات مرورگر یا کلاینت', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='اطلاعات اضافی دلخواه (برای توسعه)', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'گزارش عملیات کیف پول',
                'verbose_name_plural': 'گزارش\u200cهای عملیات کیف پول',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', 'واریز'), ('withdraw', 'برداشت'), ('transfer', 'انتقال'), ('pin_set', 'تنظیم رمز'), ('pin_verify', 'تایید رمز'), ('reward', 'پاداش'), ('fee', 'کارمزد'), ('refund', 'بازگشت وجه'), ('other', 'سایر')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('previous_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('completed', 'کامل شده'), ('failed', 'ناموفق'), ('reversed', 'برگشت خورده')], default='pending', max_length=20)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('integrity_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_reversed', models.BooleanField(default=False)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_wallet_transactions', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_wallet_transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'تراکنش کیف پول',
                'verbose_name_plural': 'تراکنش\u200cهای کیف پول',
            },
        ),
        migrations.CreateModel(
            name='WalletTransferHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='wallet.wallet')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'تاریخچه انتقال',
                'verbose_name_plural': 'تاریخچه انتقال\u200cها',
            },
        ),
        migrations.CreateModel(
            name='WithdrawRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تأیید شده'), ('rejected', 'رد شده'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_requests', to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'درخواست برداشت',
                'verbose_name_plural': 'درخواست\u200cهای برداشت',
            },
        ),
        migrations.CreateModel(
            name='ZarinPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('authority', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('payment_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('success', 'موفق'), ('failed', 'ناموفق'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('callback_data', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=256, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_payments', to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'پرداخت زرین پال',
                'verbose_name_plural': 'پرداخت\u200cهای زرین پال',
                'ordering': ['-created_at'],
            },
        ),
    ]
