# Generated by Django 5.2.4 on 2025-07-22 13:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallettransferhistory_withdrawrequest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransferhistory',
            name='reference_code',
        ),
        migrations.RemoveField(
            model_name='wallettransferhistory',
            name='status',
        ),
        migrations.AddField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallettransferhistory',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='status',
            field=models.CharField(choices=[('active', 'فعال'), ('frozen', 'مسدود شده'), ('closed', 'بسته شده')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='withdraw_limit_per_day',
            field=models.DecimalField(decimal_places=2, default=1000000, max_digits=18),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='withdrawn_today',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='previous_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'واریز'), ('withdraw', 'برداشت'), ('transfer', 'انتقال'), ('reward', 'پاداش'), ('fee', 'کارمزد'), ('refund', 'بازگشت وجه')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransferhistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='WalletErrorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_type', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_logs', to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='WalletOperationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('deposit', 'واریز'), ('withdraw', 'برداشت'), ('transfer', 'انتقال'), ('reward', 'پاداش'), ('fee', 'کارمزد'), ('refund', 'بازگشت وجه')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('success', 'موفق'), ('failure', 'ناموفق')], max_length=10)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='wallet.wallet')),
            ],
        ),
    ]
