# Generated by Django 5.2.4 on 2025-07-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_remove_wallettransferhistory_reference_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='failed_pin_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='last_failed_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
