# Generated by Django 5.2.4 on 2025-07-26 11:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_wallet_failed_pin_attempts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='walletoperationlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'گزارش عملیات کیف پول', 'verbose_name_plural': 'گزارش\u200cهای عملیات کیف پول'},
        ),
        migrations.AddField(
            model_name='walletoperationlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='آدرس IP درخواست\u200cدهنده', null=True),
        ),
        migrations.AddField(
            model_name='walletoperationlog',
            name='metadata',
            field=models.JSONField(blank=True, help_text='اطلاعات اضافی دلخواه (برای توسعه)', null=True),
        ),
        migrations.AddField(
            model_name='walletoperationlog',
            name='user_agent',
            field=models.TextField(blank=True, help_text='اطلاعات مرورگر یا کلاینت', null=True),
        ),
        migrations.AlterField(
            model_name='walletoperationlog',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='مبلغ مربوط به عملیات (در صورت وجود)', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='walletoperationlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='walletoperationlog',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='walletoperationlog',
            name='message',
            field=models.TextField(blank=True, help_text='توضیح یا پیام مرتبط با عملیات'),
        ),
        migrations.AlterField(
            model_name='walletoperationlog',
            name='operation_type',
            field=models.CharField(choices=[('deposit', 'واریز'), ('withdraw', 'برداشت'), ('transfer', 'انتقال'), ('pin_set', 'تنظیم رمز'), ('pin_verify', 'تایید رمز'), ('reward', 'پاداش'), ('fee', 'کارمزد'), ('refund', 'بازگشت وجه'), ('other', 'سایر')], max_length=20),
        ),
        migrations.AlterField(
            model_name='walletoperationlog',
            name='status',
            field=models.CharField(choices=[('success', 'موفق'), ('failure', 'ناموفق')], default='success', max_length=10),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'واریز'), ('withdraw', 'برداشت'), ('transfer', 'انتقال'), ('pin_set', 'تنظیم رمز'), ('pin_verify', 'تایید رمز'), ('reward', 'پاداش'), ('fee', 'کارمزد'), ('refund', 'بازگشت وجه'), ('other', 'سایر')], max_length=20),
        ),
    ]
