# Generated by Django 5.2.4 on 2025-07-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_zarinpayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zarinpayment',
            options={'ordering': ['-created_at'], 'verbose_name': 'پرداخت زرین پال', 'verbose_name_plural': 'پرداخت\u200cهای زرین پال'},
        ),
        migrations.AddField(
            model_name='zarinpayment',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zarinpayment',
            name='user_agent',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='zarinpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='zarinpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('success', 'موفق'), ('failed', 'ناموفق')], db_index=True, default='pending', max_length=20),
        ),
    ]
