# Generated by Django 5.2.4 on 2025-07-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_alter_zarinpayment_options_zarinpayment_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تأیید شده'), ('rejected', 'رد شده'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='zarinpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('success', 'موفق'), ('failed', 'ناموفق'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
    ]
