# Generated by Django 5.2.4 on 2025-07-30 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_alter_withdrawrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': ' کیف پول', 'verbose_name_plural': ' کیف پول'},
        ),
        migrations.AlterModelOptions(
            name='walletoperationlog',
            options={'verbose_name': 'گزارش عملیات کیف پول', 'verbose_name_plural': 'گزارش\u200cهای عملیات کیف پول'},
        ),
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'verbose_name': 'تراکنش کیف پول', 'verbose_name_plural': 'تراکنش\u200cهای کیف پول'},
        ),
        migrations.AlterModelOptions(
            name='wallettransferhistory',
            options={'verbose_name': 'تاریخچه انتقال', 'verbose_name_plural': 'تاریخچه انتقال\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='withdrawrequest',
            options={'verbose_name': 'درخواست برداشت', 'verbose_name_plural': 'درخواست\u200cهای برداشت'},
        ),
    ]
